name: CI runner

on:
  push:

jobs:
  start-albomon-runner-workflow:
    name: CI runner
    uses: zerai/albomon-executor/.github/workflows/albomon-runner.yaml@main
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"
