name: AlboMon Runner

on:
  schedule: # “At 20:00 on every day.”
    - cron: "0 12 * * *"
    #- cron: "*/5 * * * *"

  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      triggering-sha:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      albomonRepository:
        description: 'GH albomon repository'
        required: true
        default: 'zerai/albomon'
      albomonRelease:
        description: 'Release or Tag'
        required: false
        default: '0.8.3'

defaults:
  run:
    shell: bash

env:
  ALBOMON_REPOSITORY: 'zerai/albomon'
  DEFAULT_ALBOMON_RELEASE: '0.8.3'
  # ARTIFACTS SETTINGS
  ARTIFATC_NAME_FOR_APPLICATION_LOG: 'Albomon-application-log'
  APPLICATION_LOG_FILENAME: 'var/log/'
  ARTIFATC_NAME_FOR_APPLICATION_REPORTS: 'Albomon-reports'
  APPLICATION_REPORT_FILENAME: 'report/'

  #APPLICATION SETTINGS
  APP_ENV: prod
  GITHUB_TOKEN: ${{ secrets.GHA_TOKEN_ALBOMON_EXECUTOR }}

jobs:
  execute-albomon:
    name: Execute Albomon application
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      matrix:
        php:
          - '8.0'
      fail-fast: true
    steps:
      - name: Override default albomon release var
        if: ${{ env.DEFAULT_ALBOMON_RELEASE != inputs.albomonRelease && inputs.albomonRelease != '' }}
        id: override-tag-or-release
        run: echo "DEFAULT_ALBOMON_RELEASE=${{ inputs.albomonRelease }}" >> $GITHUB_ENV

      - name: Download AlboMon v.${{ env.DEFAULT_ALBOMON_RELEASE}}
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ALBOMON_REPOSITORY }}
          ref: ${{ env.DEFAULT_ALBOMON_RELEASE }}

      - name: Setup PHP
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: memory_limit=-1
          coverage: pcov

      - name: Install Dependecies
        run: |
          composer install --no-dev

      - name: Run Albomon
        id: run-albomon
        run: |
          php bin/console albomon:catalog:update --ansi
          php bin/console albomon:catalog:list --ansi
          php bin/console albomon:check:albopop-catalog --ansi

#      - name: Run catalog list
#        run: |
#          php bin/console albomon:catalog:list --ansi
#
#      - name: Run albomon
#        run: |
#          php bin/console albomon:check:albopop-catalog --ansi

      - name: Save application log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFATC_NAME_FOR_APPLICATION_LOG }}
          path: ${{ env.APPLICATION_LOG_FILENAME }}

      - name: Save report
        #needs: [run-albomon]
        #if: needs.run-albomon.result == 'success'
        #if: job.execute-albomon.steps['run-albomon'].result == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFATC_NAME_FOR_APPLICATION_REPORTS }}
          path: ${{ env.APPLICATION_REPORT_FILENAME }}
