name: Production Runner

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      triggering-sha:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      albomonRepository:
        description: 'GH albomon repository'
        required: true
        default: 'zerai/albomon'
      albomonRelease:
        description: 'Release or Tag'
        required: false
        default: '0.8.2'

defaults:
  run:
    shell: bash

env:
  ALBOMON_REPOSITORY: 'zerai/albomon'
  DEFAULT_ALBOMON_RELEASE: '0.8.2'
  # ARTIFACTS SETTINGS
  ARTIFATC_NAME_FOR_APPLICATION_LOG: 'Albomon-application-log'
  APPLICATION_LOG_FILENAME: 'var/log/'

jobs:
  execute-production-albomn:
    name: Execute Albomon - prod - (php-${{ matrix.php }})
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    continue-on-error: ${{ matrix.is-php-experimental }}
    strategy:
      matrix:
        php:
          - '8.0'
        is-php-experimental: [false]
        generate-coverage-report: [false]
      fail-fast: true
    steps:
      - name: Override default albomon release var
        if: ${{ env.DEFAULT_ALBOMON_RELEASE != inputs.albomonRelease}}
        id: override-tag-or-release
        run: echo "DEFAULT_ALBOMON_RELEASE=${{ inputs.albomonRelease }}" >> $GITHUB_ENV

      - name: Checkout on SHA-${{ inputs.triggering-sha }}
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ALBOMON_REPOSITORY }}
          ref: ${{ env.DEFAULT_ALBOMON_RELEASE }}


      - name: Setup PHP
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: memory_limit=-1
          coverage: pcov

      - name: Application install
        run: |
          composer install --no-dev
        env:
          APP_ENV: prod
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN_ALBOMON_EXECUTOR }}

      - name: Run update catalog
        run: |
          php bin/console albomon:catalog:update --ansi
        env:
          APP_ENV: prod
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN_ALBOMON_EXECUTOR }}

      - name: Run catalog list
        run: |
          php bin/console albomon:catalog:list --ansi
        env:
          APP_ENV: prod
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN_ALBOMON_EXECUTOR }}

      - name: Run albomon
        run: |
          php bin/console albomon:check:albopop-catalog --ansi
        env:
          APP_ENV: prod
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN_ALBOMON_EXECUTOR }}

      - name: Save application log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFATC_NAME_FOR_APPLICATION_LOG }}
          path: ${{ env.APPLICATION_LOG_FILENAME }}
